language: go
go: 
 - 1.6
 - 1.7
 - 1.8
 - tip

env:
  global:
    - GO15VENDOREXPERIMENT=1

before_install:

  # go vendoring - glide
  - go get -v -u github.com/Masterminds/glide

  # coverage
  - go get -v -u golang.org/x/tools/cmd/cover

install:
  - glide install

script:
  - ./go-test.sh

after_success:
  # test, collect coverage info and send to codecov
  - bash <(curl -s https://codecov.io/bash)




